version: '3.3'

services:

  postgres:
    container_name: postgres-keycloak
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak_db
        DB_USER: ${POSTGRES_USER:-postgres}
        DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin_password
      ports:
        - "8484:8080"
      depends_on:
        - postgres
      links:
        - "postgres:postgres"





  eureka-server:
    image: helpdesk/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    expose:
      - "8761"

  config-server:
    image: helpdesk/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      server.port: 8888
      eureka.client.enabled: 'true'
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  gateway-service:
    image: helpdesk/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      server.port: 8080
      eureka.client.enabled: 'true'
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - config-server