server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: histories
          uri: lb://history-service
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: tickets
            uri: lb://helpdesk-service
            predicates:
              - Path=/api/tickets/**
            filters:
              - RemoveRequestHeader= Cookie,Set-Cookie
        - id: feedbacks
            uri: lb://helpdesk-service
            predicates:
              - Path=/api/feedbacks/**
            filters:
              - RemoveRequestHeader= Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"