server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: histories
          uri: lb://histories-service
          predicates:
            - Path=/histories-service/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: helpdesk
          uri: lb://helpdesk-service
          predicates:
            - Path=/helpdesk-service/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"