server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    incude-exception: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/helpdeskdb
    username: helpdesk-user
    password: "1234qwerty"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml


keycloak:
  enabled: true
  realm: Helpdesk-app
  auth-server-url: http://localhost:8484/auth
  ssl-required: external
  resource: helpdesk-client
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: spoOt2Wroh6K8aRxoGZQsw6iynunCSDR