server:
  port: 8082


spring:
  profiles:
    active: development
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml





keycloak:
  realm: Helpdesk-gateway-app
  auth-server-url: http://localhost:8484/auth
  ssl-required: external
  resource: helpdesk-gateway-client
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: kQLLSS6xBgUTgwPgSGrWAVrWJtp7czGg