server:
  port: 8082

spring:
  application:
    name: history-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/helpdeskhistorydb
    username: helpdesk-history-user
    password: "1234qwerty"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          show_sql: false
          temp:
            use_jdbc_metadata_defaults: false
          format_sql: false
    liquibase:
      change-log: classpath:/db/changelog/db.changelog.xml

  profiles:
    active: development
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml

keycloak:
  realm: Helpdesk-gateway-app
  auth-server-url: http://localhost:8484/auth
  ssl-required: external
  resource: helpdesk-gateway-client
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: kQLLSS6xBgUTgwPgSGrWAVrWJtp7czGg

management:
  endpoints:
    web:
      exposure:
        include: "*"